#!/bin/sh
#this script sets the wallpaper as gif

killall xwinwrap

xwinwrap -g 3840x2160 -ov -ni -s -nf -- mpv -wid WID ~/media/pics/gifs/cityscape1.gif --no-osc --no-osd-bar --loop-file --player-operation-mode=cplayer --no-audio --panscan=1.0 --no-input-default-bindings
