#!/bin/sh

xrandr --output HDMI-0 --mode 1920x1080 --pos 3840x0 --rotate normal --scale 2x2 --output DP-2 --primary --mode 3840x2160 --pos 0x0 --rotate normal --scale 1x1 --panning 3840x2160

nitrogen --restore
